[theme]
primaryColor = "#aec3b0"
backgroundColor = "#124559"
secondaryBackgroundColor = "#598392"
textColor = "#eff6e0"
font = "sans serif"
base = "dark"

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"
